### ISSUE TITLE
Give additional examples of sets that don't enter Standard

### ISSUE THREAD

**Issue by NilsEnevoldsen** [glacials/whatsinstandard#100]
The website clarifies that "Masters sets never enter Standard." I'm not sure why Masters sets are singled out in this way, as Commander sets, Battlebond, and so forth are in the same situation.

**Comment by glacials** [comment]
Some history about it in #28, tldr being that there is confusion and I guess Masters is just a bigger example of where that confusion happens. I'm not against clarifying this to include other types of sets, either by name or with a catchall. I don't think the fix is to remove it.

**Comment by NilsEnevoldsen** [comment]
I see. Yes, maybe adding a few other common set types would make this line stand out less.

**Comment by NilsEnevoldsen** [comment]
Suggested:

> Not all sets enter Standard upon release. For example, Masters sets and Commander sets do not enter Standard.

**Comment by forstermatth** [comment]
I like it, clarifies that not just masters sets are not the only non-standard releases.

**Comment by glacials** [comment]
Yeah that sounds great to me!
