### ISSUE TITLE
ORI Icon

### ISSUE THREAD

**Issue by hoganlong** [glacials/whatsinstandard#12]
![ori_setsymbol](https://cloud.githubusercontent.com/assets/192723/8337911/bce09c26-1a7b-11e5-870b-77a14876b678.png)

**Comment by glacials** [comment]
Thanks! I don't like to include icons for unreleased sets though, to help stress the differences between the released + unreleased styles. I will include this next month when ORI releases, and will also hunt around for an SVG version first.

**Comment by hoganlong** [comment]
... and here I thought I was being so darn helpful.

Thanks for the very useful site.
