### ISSUE TITLE
There is no api file hosted on the repo anymore?

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#127]
I only find the `internal.json` which has a note in their comments to not be used as API. There used to be a sets.json in the v5 folder.

**Comment by glacials** [comment]
Correct! It is gone from the repo. It is now generated at build time by running `npm install`. The production deploy automatically does this, so it is still in place at https://whatsinstandard.com/api/v5/sets.json. This makes it easier to maintain multiple API versions.
