### ISSUE TITLE
unreleased sets are not clickable and linked to scryfall

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#132]
Even when sets are not officially released scryfall has cards for them already.

Worst case would be an error page like [this](https://scryfall.com/sets/idk).
But I doubt that there is no single card spoiled by the time it shows up on your webpage.

**Comment by glacials** [comment]
Good point, thanks :) There have been a few in the past with no spoilers, but recently Wizards has not been releasing set info ahead of time -- we don't even know what the next set is, 1 day before release :O

But I agree, better to link and risk an error page than to not link.
