### ISSUE TITLE
M19 not being displayed as leaving standard

### ISSUE THREAD

**Issue by Bertral** [glacials/whatsinstandard#134]
Core Set 2019 is leaving standard in September of this year and isn't displayed as such since the new design of whatsinstandard.com. It was correct bofore that.
Here's a [screenshot](https://i.imgur.com/pr17psW.png). Same problem in chrome and firefox.

**Comment by gabbes** [comment]
I think you misinterpret the design, it's a progress bar visually indicating how long the above sets have left in their standard lifespan. Not an indicator of which of the above sets are leaving. Although it admittedly might quite look like that when the progress bar aligns right at the border of two sets.

**Comment by Bertral** [comment]
You're right, I didn't see it could be a progress bar.
