### ISSUE TITLE
Release date for next two MTG sets

### ISSUE THREAD

**Issue by k94ll13nn3** [glacials/whatsinstandard#148]
Theros: Beyond Death is coming January 24, 2020.
Ikoria: Lair of Behemoths is coming April 24, 2020.

Source: https://magic.wizards.com/en/products

**Comment by nodarsan** [comment]
I just create a PR for this:
https://github.com/glacials/whatsinstandard/pull/149

**Comment by glacials** [comment]
Closed by #149 :)
