### ISSUE TITLE
Increase visual differency between former/future and currently legal sets

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#153]
The grey color used to differenciate sets that used to be legal and the ones which are going to be released in the future is not very well distinguishable from the currently legal sets.

Did you thought about using bold text for the current standard sets?
Or using an even lighter grey for the not legal ones? On hover it could get a bit darker again.

**Comment by glacials** [comment]
Yeah I agree, I'm not happy with how it is right now. I'd look at any PRs that try to fix this!

I will say I'd want any fix to use native Bootstrap classes / styling / etc. wherever reasonable, because it's easier to maintain with regards to design and accessibility (contrast ratio is a real concern here), especially for someone like me who's not all that great at design.

**Comment by troyfitzwater** [comment]
I could try a couple of different solutions. What about using different colors to distinguish between the two? For example, having a shade of red that's for sets that are no longer in standard. 

Another solution could be doing something similar with color but having it applied very lightly to the background for each set's box in a way that is still accessible in regards to contrast.

**Comment by troyfitzwater** [comment]
![whatsinstandard_changed_set_text](https://user-images.githubusercontent.com/47371758/69922839-a6c2da80-146d-11ea-983a-c3df0c0a37c2.PNG)

Here's one way I thought could work. The "text-danger" Bootstrap class was applied to the previous sets' text and meets WCAG AA standards for contrast, but neither of their blue text classes met AA or AAA standards, so I made my own that meets both. Let me know what you think.

**Comment by silasary** [comment]
I like it

**Comment by tooomm** [comment]
Hmm, it's not ideal though.

I feel like the colors stress the sets which are least important even more.
They are visually more differentiated and there is a higher contrast, that's true.
Just that the focus is not on point.

Did you try some opacity as well @troyfitzwater?
Or my suggestion from above to have the currently legal sets additionally in bold?
I think the set icons of former sets should be in the same red color. Looks like they had some opacity applied to them already?

**Comment by troyfitzwater** [comment]
@tooomm I see what you mean. I'll play around with the opacity, while keeping the accessibility in check, and make the current sets bold. I'll checkout the opacity on the icons, too. 

Thanks for the suggestions.

**Comment by troyfitzwater** [comment]
![whatsinstandard_bold_text_with_color](https://user-images.githubusercontent.com/47371758/69993263-746eb700-1519-11ea-9cd1-041c677dee00.PNG)
![whatsinstandard_bold_text_without_color](https://user-images.githubusercontent.com/47371758/69993273-79336b00-1519-11ea-818a-58ba37becd60.PNG)

I made the current sets bold and tried messing with the opacity, but going any lower would no longer meet WCAG requirements. I also made the icons match the red. 

The previous muted text was meeting AA requirements, so I included a picture of what it would look like with just making the current sets bold without adding color. The visual hierarchy alone could be enough to differentiate them. 

Again, let me know what everyone thinks.

**Comment by glacials** [comment]
Thanks for owning this @troyfitzwater! I agree with @tooomm, even on this new version at best they all seem of equal importance. I feel like there must be something more creative we can do. Maybe font size? Or maybe showing only one section at time, requiring clicks to move between them?
