### ISSUE TITLE
Remove obvious and repetitive information/label from page

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#154]
Currently, the page repeats itself several times with the labels for each group of leaving and entering sets.
It always sais "left Standard `day of week, date year`" or "in Standard until `quarter year`".
The page is only about standard format, so why write it for every box again? The term `Standard` is already used 19x on the page... I think people know. :)
Just tell them the important information without repeating the format.

Instead, it could be named `left x`, `leaving x`, `legal until x`, `playable until x`...

Especially with mobile devices in mind, screen space is important and the information doesn't add value.

**Comment by glacials** [comment]
Really good point, can't unsee all the "Standard"s on the page now 😆
