### ISSUE TITLE
Hovering an upcoming set should show a border of the element

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#156]
The new, upcoming set in the top right is selected with the mouse:
![hover](https://user-images.githubusercontent.com/9874850/71326249-9051f100-24f8-11ea-9e51-b59a58e31c15.png)

Only the text is underlined to advertise that it's a clickable link.
It would be a nice visual support to show a border around all element on hover just like the boxes for already available sets show constantly. To get a feeling of a button and to more easily connect which information belongs together.

**Comment by troyfitzwater** [comment]
So do you think there should be a border on-hover, but not a change in the background color like the released sets have on-hover, to keep some visual difference between the two?

I can play around with this and post how it looks.

**Comment by tooomm** [comment]
Even on hovering, the background color should never be the same as for legal sets. Maybe only the border is enough.

Looking forward to the results you come up with.

**Comment by troyfitzwater** [comment]
Here's what I have, its pretty simple, just shows up after hovering over it.
![Illegal_Set_Border_After_Hover](https://user-images.githubusercontent.com/47371758/81023768-695ce180-8e3f-11ea-9266-ddb45243d063.png)

There could also be a light border when there is no hover, if that looks appealing at all.
![Illegal_Set_Border_Before_Hover](https://user-images.githubusercontent.com/47371758/81023857-ba6cd580-8e3f-11ea-8412-07751afb9e19.PNG)

Thoughts?

**Comment by tooomm** [comment]
@troyfitzwater Cool. I think it looks best if the border is the same thickness and colour than the other boxes. In your first example it's black and thicker which doesn't match the other border styles?

Always displaying the border for upcoming sets looks really nice, too! But then again, I miss some form of highlighting once you hover/select one of the "upcoming set" tiles... 
Maybe use the thicker and darker coloured border for all boxes on hover in that case, next to the additional background colour change for the currently standard legal sets?

**Comment by troyfitzwater** [comment]
@tooomm Thanks for that feedback! I did what you suggested in that last paragraph and put the border on everything, while keeping that faded border for the unreleased sets.

![border_on_released_set](https://user-images.githubusercontent.com/47371758/81237796-76f4a180-8fce-11ea-8a65-f42db2bea4a1.png)

Tweaking the thickness, color, etc of the border can be done, too, if you think it could look better.

**Comment by tooomm** [comment]
It looks good as far as I can tell.
I would need to see it deployed somewhere to judge.

**Comment by troyfitzwater** [comment]
Gotcha, this is my first time contributing to open source, so I'm still learning how this process works. Do you think I should just send a pull request along and link this issue at this point?

**Comment by tooomm** [comment]
There is no general process to follow. Ever project and every maintainer has his own preferred ways...

In general it's good to discuss things in an issue ticket before opening a PR right away. 👍 
I think it's totally fine to open a PR for this now and get some more feedback. Try to write "Fixes #XXX" (with X being the issue number of this ticket) at the very beginning in its description to reference this. Also, with that wording this issue will close automatically once the PR is merged.
