### ISSUE TITLE
Hearthstone refuse to connect error

### ISSUE THREAD

**Issue by josephprice** [glacials/whatsinstandard#160]
When I go to whatsinstandard.com and click on the Hearthstone link, I get a refuse to connect error.
![image](https://user-images.githubusercontent.com/1693480/78576083-343a8080-77fa-11ea-9507-3a62243e7ff4.png)

**Comment by glacials** [comment]
Thanks for the report! That site is not maintained by me, it is a cross-link to a fork of this project maintained by another person.

That person recently emailed me saying they're shutting it down citing their declining interest in the game and lack of visitors, so I will go ahead and remove the link. If any passers-by want to take up the reigns, the code is at [bdzs/whatsinstandard](https://github.com/bdzs/whatsinstandard).

**Comment by josephprice** [comment]
That sounds like the right call! Thank you for whatsinstandard.com!
