### ISSUE TITLE
Hide left sets layout problem

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#165]
https://github.com/glacials/whatsinstandard/pull/164 introduced this issue most likely.

Borders should not show there on hover. Also, the layout jumps a bit once the border is drawn for left sets.

CC: @troyfitzwater 

Screenshot:
![left](https://user-images.githubusercontent.com/9874850/92979256-5fed2100-f492-11ea-82eb-7a25d34ea4bc.png)

**Comment by troyfitzwater** [comment]
Hey there! Been a while, but I will look into this!

Just to clarify, what should the desired behavior be for the left sets? Just the typical underline on hover?

**Comment by tooomm** [comment]
Underline sounds fine imo. That should also remove the "jumping".

**Comment by tooomm** [comment]
I like the result way better - thanks for taking care @troyfitzwater 👍
