### ISSUE TITLE
Icons missing (keyrune outdated)

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#168]

**Comment by glacials** [comment]
Fixed by dae43c577762fe440c29ff018bf52e3b6800a664, thanks!

**Comment by tooomm** [comment]
I saw that you had dependabot updating some packages recently... it could automatically create PR's for new keyrune versions for you to check and merge as well.

**Comment by glacials** [comment]
Thanks, didn't know I could configure it! This will be very helpful.

**Comment by tooomm** [comment]
You added a config.yml inside a `.dependabot` folder. I think that's for the legacy, standalone version of dependabot. Not sure if that works as long as you doesn't sign up for their service.

Now that they are part of github you want to use the native, integrated version which uses a dependabot.yml file (see https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates).
Looking at the former dependabot PR's in the repo, you are using the integrated version already and probably enabled dependabot security updates in the repo settings. Otherwise the created PR will be from `dependabot-preview` and doesn't have the github icon attached.

**Comment by glacials** [comment]
Ah, gotcha! Should be fixed now, the GitHub UI is showing as working under Insights. Thanks!

**Comment by tooomm** [comment]
Cool, thanks for taking care. I guess that's a very handy addition.
Let's see how it goes!
