### ISSUE TITLE
A favicon

### ISSUE THREAD

**Issue by glacials** [glacials/whatsinstandard#17]
would be nice.

**Comment by glacials** [comment]
When one is made, also add it to the manifest file (see #19) so that Android users get it as an icon when they add the site to their home screens.

Also add it as an iOS icon for similar reasons.

**Comment by jordanbrauer** [comment]
I noticed you haven't gotten around to making this change (or any really lol). 

Are you accepting contribution, or is this just your personal repo?

**Comment by Nightfirecat** [comment]
Contributions are accepted.

**Comment by glacials** [comment]
^ this! I'm not a designer but I like to keep track of todos :)

**Comment by DuffyElmer** [comment]
@glacials I'm new to Github, where do I UL a favicon?
![favicon-16x16](https://user-images.githubusercontent.com/28229677/31052671-6f29a146-a640-11e7-93dc-ee30f3b2d7ef.png)
![favicon-32x32](https://user-images.githubusercontent.com/28229677/31052672-7369cbfa-a640-11e7-8294-abc0608c91c5.png)
![favicon-96x96](https://user-images.githubusercontent.com/28229677/31052673-755d6afc-a640-11e7-850a-007f91a8d650.png)

**Comment by silasary** [comment]
I assume that adding it to the repo as `favicon.ico` should be enough?

**Comment by glacials** [comment]
Thanks! However I'd prefer to use original artwork rather than lifting something off of Magic.

**Comment by csuhta** [comment]
@glacials What about something like this? 

![favicons](https://user-images.githubusercontent.com/769083/41451522-472742d2-703b-11e8-9088-93ba5cd28e47.png)

(Grey background to show the transparent areas)

**Comment by NilsEnevoldsen** [comment]
Throwing my hat into the ring.

![whatsinstandard](https://user-images.githubusercontent.com/222743/41492056-92238f86-70ca-11e8-96ff-ddfb842c24ad.png)
![whatsinstandard](https://user-images.githubusercontent.com/222743/41492045-7fb93d00-70ca-11e8-9a9a-ca698cbc3622.png)

**Comment by glacials** [comment]
Wow nice! These are both great, thanks for creating them both of you!

Stylistically I like them both equally! But @NilsEnevoldsen yours relates back to Magic so I think that one would be a bit more relevant. Mind opening a PR? And can you confirm this is original artwork?

**Comment by NilsEnevoldsen** [comment]
Yes, it's original. I tweaked it slightly and opened a PR. I included the original SVG if you want to make modifications yourself. I made a few judgment calls about theme colors on various platforms based on what seemed to work best. I kept everything grayscale or transparent except the Metro theme, where I used Metro's "blue".

**Comment by NilsEnevoldsen** [comment]
Things to verify:
- [ ] Does it look good in the tab bars of all major browsers on all major OSes (including Safari 12 Technology Preview)?
- [ ] Does it look good pinned to iOS home screen?
- [ ] Does it look good added to Android Homescreen by Chrome?
- [ ] Does it look good pinned to the Metro desktop?
- [ ] Does it look good as an unfocused pinned tab in Safari on macOS?
- [ ] Does it look good as a focused pinned tab in Safari on macOS?
- [ ] Does it look good in the touch bar on macOS?
