### ISSUE TITLE
Adventures in the Forgotten Realms `enter_date` is the online release date, not paper

### ISSUE THREAD

**Issue by bakert** [glacials/whatsinstandard#199]
This was added in 37a113b9b and probably just "missed". The policy described in #159 suggests that the site and API will reflect paper dates.

I wonder if it should be a deliberate policy change? Probably the only sensible thing is to provide two `enter_date`s for each or an alternative `online_enter_date`. If it were additive could it be considered not a breaking API change and added to v6? I can put up a PR.

It's affecting the display dates of the season-ending Penny Dreadful 500 and our rotation date currently. We don't want those to suddenly "jump" after everyone has seen that they are in 2/3 weeks respectively.

**Comment by bakert** [comment]
This was fixed. Looks like the dates for the two Innistrad sets added at the same time match the only released dates so far. It will be interested to see if they turn out to be the MTGO/Arena dates and not the paper dates as we get closer. I suspect so.

**Comment by riQQ** [comment]
Fixed with f2a7f8440f75b9abe108b4b6460831663e66cf78

When I added the AFR date back then, I think it was the only available date. But it was given in an Arena article. And now the old date is neither the Arena / MTGO release nor the paper release :D

**Comment by bakert** [comment]
This probably means that the dates we currently have for the two Innistrad sets are online dates.

**Comment by silasary** [comment]
The source for the Innistrads was https://magic.wizards.com/en/articles/archive//news/strixhaven-school-mages-previews-and-more-2021-magic-release-dates-2021-03-18

But it looks like Midnight Hunt was delayed by a week since it was first published, I'll send a PR with the new date
