### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by zombisound** [glacials/whatsinstandard#20]
"The Khans of Tarkir block and Magic Origins, although released in the old pattern, are dropping in the new: Khans of Tarkir and Fate Reforged dropped together in April as if they were a two-set block; Dragons of Tarkir and Magic Origins will drop in the same fashion Q4 2017."

Should be Q4 2016

**Comment by glacials** [comment]
Woops, thanks! Should be fixed now.
