### ISSUE TITLE
GitHub icon moves when toggling recently dropped sets

### ISSUE THREAD

**Issue by glacials** [glacials/whatsinstandard#21]
The GitHub Octocat icon in the bottom-right changes position when toggling the recently dropped sets display at the top of the page.

**Comment by Nightfirecat** [comment]
Where would you ideally want it? Right now, it's based on the bottom-most position of the content which changes after toggle. It'd be simple enough to just stick it to the bottom-right of the page.

**Comment by glacials** [comment]
Bottom-right would be fine. I think when I tried it previously I ran into a problem on mobile devices where it would overlap with the last sentence of text. If it can be down there without that happening, :ok_hand:.
