### ISSUE TITLE
Cross-link standardhearth.com for visibility

### ISSUE THREAD

**Issue by Nightfirecat** [glacials/whatsinstandard#23]
I'd open an issue on [bdzs/whatsinstandard](https://github.com/bdzs/whatsinstandard) as well, but that repo doesn't have issues open. (@bdzs)

Ref: https://github.com/glacials/whatsinstandard/pull/22#issuecomment-209221651

**Comment by bdzs** [comment]
Just enabled issues!

And yeah this crosslinking thing is a good idea, will do it!
