### ISSUE TITLE
Incorrect remaining time until release when only rough enter date is known

### ISSUE THREAD

**Issue by riQQ** [glacials/whatsinstandard#276]
An incorrect remaining time until release is shown when only the rough enter date is known. It should rather display something like 3-5 months.

Screenshot taken on 2024-01-05:
![screenshot showing the problem](https://github.com/glacials/whatsinstandard/assets/3404787/d2ebb4ae-47a2-45e3-8381-d6de7b877e50)

https://github.com/glacials/whatsinstandard/blob/cbd18b54ae6f8b412adc93b41189c0e2972d660f/web/api/internal.json#L340-L349

**Comment by glacials** [comment]
Thanks, agreed this is an issue. Will gladly accept a PR, otherwise will fix when I find the time.
