### ISSUE TITLE
Clarify that nonstandard sets aren't Standard

### ISSUE THREAD

**Issue by glacials** [glacials/whatsinstandard#28]
...that sounds dumb now that I say it.

There's sometimes confusion about Duel Decks or Commander or whatever, where e.g. a new one just released and you don't see it on WIS so you might think that it's missing by accident, instead of just not Standard. We should remove all doubt and specifically say these types of sets never enter Standard.

**Comment by barbier** [comment]
I came here just to ask if Eternal Masters is Standard, I think a section on the site can do it.
Do you like this idea? Is there an easy way to get this kind of data?
