### ISSUE TITLE
The Big Score (BIG) is missing

### ISSUE THREAD

**Issue by RivalRowan** [glacials/whatsinstandard#300]
[The Big Score](https://magic.wizards.com/en/news/feature/collecting-outlaws-of-thunder-junction) is a bonus sheet included with the Outlaws of Thunder Junction (OTJ) release. The set includes 30 cards, all mythic rare.

Originally it was designed as a stand-alone release, similar to _March of the Machine: The Aftermath_. Once that set failed, the stand-alone release was cancelled and the set was added to OTJ as a bonus sheet. The cards remained Standard-legal though.

**Why separate this out from OTJ?**
Good question, it's because the _other_ bonus sheet included in the set (Breaking News) is _not_ Standard-legal. This would also align the set with the _March of the Machine: The Aftermath_ release. The Big Score has it's own set code, set symbol, and a unique history.

The following should be added to the .JSON:
    {
      "name": "The Big Score",
      "codename": null,
      "block": null,
      "code": "BIG",
      "enter_date": "2024-04-19T00:00:00.000",
      "rough_enter_date": "Q2 2024",
      "exit_date": null,
      "rough_exit_date": "Q1 2027"
    },

**Comment by glacials** [comment]
Thanks! Would accept a PR.

**Comment by RivalRowan** [comment]
Sorry, haven't had the time to set one up. Did you still want the PR?

**Comment by glacials** [comment]
Yes please! I also have had zero time recently.

**Comment by RivalRowan** [comment]
Thanks for the merge!
