### ISSUE TITLE
Add Kaladesh and Aether Revolt?

### ISSUE THREAD

**Issue by Ketsuban** [glacials/whatsinstandard#31]
We know their names, and there's already a recently-dropped sets block; including the next sets to be rotated in might help people get a handle on what's going on when (for instance) Reddit explodes with excitement about Eternal Masters.

**Comment by LPGhatguy** [comment]
I opened a pull request to potentially address this, but it may not be properly formatted.

**Comment by glacials** [comment]
Resolved by said PR, closing!
