### ISSUE TITLE
The link "show recently dropped sets" should change to "hide" after clicking

### ISSUE THREAD

**Issue by heymattlauer** [glacials/whatsinstandard#33]
I noticed that clicking the "show recently dropped sets" link reveals the dropped sets, but the link text remains "show recently dropped sets" after clicking. This is non-intuitive, especially if clicking that link again _hides_ those recently dropped sets.

I'd recommend changing the link text to "hide recently dropped sets" after revealing the dropped sets by clicking, and change it back to "show recently dropped sets" on toggling it again.

**Comment by glacials** [comment]
Agreed, good suggestion.

**Comment by heymattlauer** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8583417-125456932_2-s1-v1.png?palette=1&width=246)
