### ISSUE TITLE
API v4

### ISSUE THREAD

**Issue by glacials** [glacials/whatsinstandard#34]
Now that the 2-year transition between the old set release pattern and the new is over, we can remove the ability for the `block` field in the API to be null. There are a couple of other changes I'd like to make as well, like changing the `rough_exit_date` format to use quarters rather than "late" or "early/mid". I also might remove the `symbol` field, as this is not easy to maintain now that our in-page set icons use a font rather than images.

**Comment by dgant** [comment]
I recently started using the whatsinstandard API for ComboDeck (thanks!) to keep its Standard legality in sync with rotations.

When a set is about to rotate into Standard, it seems that most people are interested not in what's currently in Standard, but what's about to be in Standard. For ComboDeck, that'd mean letting people filter cards not just by (What's in Standard) but also (What's in Standard as of the next rotation). 

So if the API included information about upcoming Standard sets, that'd be quite handy!

Thank you for running whatsinstandard!

**Comment by glacials** [comment]
Thanks for the explanation, I can definitely do that!

**Comment by glacials** [comment]
There you go!

**Comment by dgant** [comment]
Awesome! I'll work this in.
