### ISSUE TITLE
They changed it back to a yearly rotation schedule

### ISSUE THREAD

**Issue by ryandietrich** [glacials/whatsinstandard#35]
http://magic.wizards.com/en/articles/archive/news/revisiting-standard-rotation-2016-10-19

**Comment by dgant** [comment]
All the more reason why the whatsinstandard API is awesome!

**Comment by glacials** [comment]
:o

**Comment by glacials** [comment]
Thanks for bringing this up :)

**Comment by HoopyHobo** [comment]
Why does the main page still say "Until April 28, 2017" under BFZ-block?

**Comment by glacials** [comment]
Woops, missed the most important one! Good catch, should be fixed now. Thanks!
