### ISSUE TITLE
Welcome Deck 2017

### ISSUE THREAD

**Issue by HoopyHobo** [glacials/whatsinstandard#48]
[W17](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=[%22Welcome%20Deck%202017%22]) is now Standard legal.

**Comment by forstermatth** [comment]
@HoopyHobo Do you know if it contains any cards that are not in the current sets?

**Comment by forstermatth** [comment]
Answered my own question - yes it does; http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=413367 for example.

**Comment by HoopyHobo** [comment]
W16 is already accounted for under SOI, and Aegis Angel is the White Rare from W16. In W17 it has been replaced by [Victory's Herald](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=429895). So yes, both W16 and W17 contain cards that are not present in any other Standard-legal sets.

**Comment by forstermatth** [comment]
Thanks for the clarification.

**Comment by glacials** [comment]
Thanks!
