### ISSUE TITLE
Question about exit_dates

### ISSUE THREAD

**Issue by inuyasha82** [glacials/whatsinstandard#50]
Hi, 
according to the documentation exit_date is the date the set exits standard format, and looking at battle for zendikar block: 

`
  {
    "name": "Battle for Zendikar",
    "block": "Battle for Zendikar",
    "code": "BFZ",
    "enter_date": "2015-10-02T00:00:00.000Z",
    "exit_date": "2017-04-28T00:00:00.000Z",
    "rough_exit_date": "Q4 2017"
  },

  {
    "name": "Oath of the Gatewatch",
    "block": "Battle for Zendikar",
    "code": "OGW",
    "enter_date": "2016-01-22T00:00:00.000Z",
    "exit_date": "2017-04-28T00:00:00.000Z",
    "rough_exit_date": "Q4 2017"
  },
`
Both blocks should be out of standard now. But this is not true, and it will happen this fall. (i think that the exit date will be 2017-09-29. That anyway is correct in the rough exit date.

I think that the dates refer to the old rotation format (twice per year), that has recently changed.

**Comment by glacials** [comment]
Closed by #51
