### ISSUE TITLE
Needs Update due to Standard Rotation (MtG)

### ISSUE THREAD

**Issue by DuffyElmer** [glacials/whatsinstandard#64]
The current frontpage still shows BFZ and SOI blocks as being in standard. These should be moved to the recently dropped sets list, along with Reflector Mage and Emrakul being removed from the banlist. DTK/Origins should likely be removed as they are no longer the most recently dropped sets.

**Comment by glacials** [comment]
Thanks! Fell behind a bit. More automation changes coming soon so that nothing needs to be manual on rotation.

**Comment by DuffyElmer** [comment]
Thanks, dude!
