### ISSUE TITLE
API v6 TODO

### ISSUE THREAD

**Issue by glacials** [glacials/whatsinstandard#65]
Definitely way too soon and very little reason to bump API versions, but when it does happen this is a living list of things to remember to change.

- Change API from `snake_case` to `camelCase` per Google's JSON style guide

**Comment by glacials** [comment]
Few new items:

* *Ravnica Allegience* has a month of release ("January 2019") but no date. The API should either allow partial dates or allow `enter_date` to be null.
* Unofficial blocks: there are three Ravnica sets coming, all blockless because blocks don't exist but thematically together. Should we express that in the API? Maybe optionally.
* On that note, kill the `block` field if all the sets that use it have dropped by the time v6 is implemented.
* Nation-specific legality: The [recent China announcement][1] makes determining what is in Standard a country-specific question. If you're in China the answer is different from if you're anywhere else. The API probably needs to support this.

[1]: https://magic.wizards.com/en/articles/archive/news/global-series-meet-jiang-yanggu-and-mu-yanling-2018-05-18

**Comment by silasary** [comment]
"Archery" releases on October 4, 2019, but because we don't have a name yet, it's not in the API.

**Comment by glacials** [comment]
I've just released v6 and addressed all these issues except nation-specific legality and thematic blocks. These two items aren't vital and could be added later with a non-breaking change, so for now I'll forward them on to the equivalent v7 issue.
