### ISSUE TITLE
Bans in the API

### ISSUE THREAD

**Issue by glacials** [glacials/whatsinstandard#67]
Brought up in #66, it would be great to have bans in the API so that API consumers can use them and so that no action has to be performed by us on dates when bans come into / out of effect.

**Comment by inuyasha82** [comment]
How these information should be presented? 
We should add them in the sets.json, and keep everything in the same response, or should be better to create a new endpoint (i.e. /bans) that returns only the ban? 

I vote for the second option.

**Comment by glacials** [comment]
The second option is conceptually cleaner, but causes more work for consumers. Since both responses are very small, I'd prefer to do the first option and combine them into one endopoint.

**Comment by silasary** [comment]
Conceptually, I'm against it being part of `/sets.json`, but I think that is more an issue about naming than the seperation itself.

As such, I'd suggest putting bans in the main json file, but renaming it to something like `standard.json` when v6 hits.
