### ISSUE TITLE
Brawl Information?

### ISSUE THREAD

**Issue by connor-bracewell** [glacials/whatsinstandard#73]
Seeing as [the new Brawl format](https://magic.wizards.com/en/articles/archive/ways-play/join-brawl-2018-03-22) announced by Wizards is going to use the same rotation/ban list as Standard, I suspect *What's in Standard* will become a commonly-shared resource for that community as well.

Should the site include some brief information about Brawl, or should it remain 100% focused on Standard only? Thoughts?

**Comment by glacials** [comment]
Yeah it's maybe worth a sentence. "The *Brawl* format is based on *Standard*, so rotations and bans listed here also apply to *Brawl*." or something.
