### ISSUE TITLE
DOM release currently reported as one day early

### ISSUE THREAD

**Issue by csuhta** [glacials/whatsinstandard#75]
<img width="491" alt="9smrgbquzj" src="https://user-images.githubusercontent.com/769083/39213892-c5a9cb76-47e0-11e8-83d6-0da38411fba9.png">

**Comment by Nightfirecat** [comment]
I'm not seeing that behavior.

![untitled](https://user-images.githubusercontent.com/2199511/39215032-049f859e-4806-11e8-834b-aa56fafc0258.png)

Furthermore, the code is correct: https://github.com/glacials/whatsinstandard/blob/master/api/v5/sets.json#L104

Possibly a Javascript timezone/clock issue?

**Comment by csuhta** [comment]
If the code localizing `2018-04-27T00:00:00.000Z`into the current browser's timezone, that will result in some some people seeing the day before or after the 27th, which is not correct.

Dominaria releases at midnight on April 27 in each time zone, not at exactly the time 2018-04-27 00:00 UTC

These dates should be interpreted a "calendar dates" without a time zone, not as full localizable timestamps

**Comment by glacials** [comment]
Thanks yall, should be fixed!
