### ISSUE TITLE
Character encoding of the HTML document is not declared as UTF-8

### ISSUE THREAD

**Issue by NilsEnevoldsen** [glacials/whatsinstandard#80]
Right now dashes are rendering as `â€”`: `Brawl is partially based on Standardâ€”all rotations listed here apply to Brawlâ€”but Brawl has a separate banlist.` This is because the character encoding of the HTML document is not declared, and it is falling back to Windows-1252 (at least on Safari, Chrome, and Firefox on macOS).

**Comment by glacials** [comment]
Thanks for noticing and diagnosing!! I switched us to Google Cloud Storage hosting last night to try it out so I assume it only worked before that because GitHub Pages passed a header that filled the same purpose.
