### ISSUE TITLE
Add Core Set 2020

### ISSUE THREAD

**Issue by NilsEnevoldsen** [glacials/whatsinstandard#83]
The name of the next core set is known: _Core Set 2020_.

**Comment by glacials** [comment]
Unfortunately we don't have the code in place to name a set that comes out after a set that we don't yet have a name for, so I'll leave this open until we know the name of the last Ravnica set. I'll also add this to #65 as something to support for the next API.

**Comment by silasary** [comment]
I mean, given than _Masters 25_ was given `A25` to prevent conflicts with the core set, I think we can make an assumption here.

**Comment by NilsEnevoldsen** [comment]
@silasary, I think @glacials is saying that since we don't know the set name of Milk, we can't add Core 2020.

**Comment by glacials** [comment]
Oops yeah, poor phrasing on my part. "Code" as in JavaScript, not as in the set's `M20` code.

**Comment by tooomm** [comment]
@NilsEnevoldsen it helps if you always link to a (official) source regarding new sets to get the naming and date etc. right

**Comment by NilsEnevoldsen** [comment]
https://magic.wizards.com/en/articles/archive/making-magic/more-odds-ends-core-set-2019-2018-08-06 gives "Core Set 2020". Embarrassingly, I created the issue with the wrong name ("*Core 2020*").

**Comment by NilsEnevoldsen** [comment]
Oh, I see, I did that because whatsinstandard had the wrong name for 2019.

**Comment by NilsEnevoldsen** [comment]
https://magic.wizards.com/en/articles/archive/news/announcing-core-set-2020-and-commander-2019-edition-2019-02-21
