### ISSUE TITLE
API unavailable from repo

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#89]
There is no more API available at all, I can't find the `.json` file which used to be here:
https://github.com/glacials/whatsinstandard/tree/master/api/v5

**Comment by glacials** [comment]
The way the API is generated has changed recently, and it is now generated at build-time from other files, so it will not be visible here on GitHub. However it should still be there at the same URL it has always been. Can you see if you can access it? https://whatsinstandard.com/api/v5/sets.json

(Regardless I can try to make this clearer through documentation.)

**Comment by tooomm** [comment]
The https://whatsinstandard.com/api/v5/sets.json url works and the API is accessible there 👍 
For the same reasons stated in #88 I used the file in the github repo though...
