### ISSUE TITLE
Pokémon version?

### ISSUE THREAD

**Issue by barbier** [glacials/whatsinstandard#90]
Since the app have versions for MTG and Hearthstone, how hard is to create a version for the Pokémon TCG?

**Comment by glacials** [comment]
The Hearthstone version was made by @bdzs ([bdzs/whatsinstandard](https://github.com/bdzs/whatsinstandard)) forked from my code, and we agreed to cross-link the two sites. If you or someone else makes a version for Pokemon I'd be happy to do the same. I do not want to get into the business of maintaining a website for a game I don't know anything about :)

**Comment by playwithbear** [comment]
Has there been any other movement on this issue? Because I'd be happy to start working on something like this for Pokemon :-)

**Comment by bdzs** [comment]
I've never played Pokemon TCG and pretty much don't know anything about their card system so it's pretty much up to you I guess! But sounds good I guess, I mean it's a good idea to have one for Pokemon TCG as well!

**Comment by playwithbear** [comment]
I've got it up at standardpokemon.tk I'd appreciate it if you could add it to your nav. I'd do a pull request updating just that but obviously don't have permission.

**Comment by glacials** [comment]
Looks great @playwithbear! My one request is that you enforce HTTPS on your site. It looks like you already support it, but it is not enforced. Once you do I'm happy to cross-link.

**Comment by playwithbear** [comment]
Done. Was trying to do it before but GitHub was having issues with itself... :-D

**Comment by glacials** [comment]
Thanks :) All linked up!

**Comment by bdzs** [comment]
Linked too! Sorry I was offline...
