### ISSUE TITLE
Current Sets in Standard not Listed?

### ISSUE THREAD

**Issue by DominusMaximus** [glacials/whatsinstandard#91]
The sets being dropped and the ban list is very useful, but how can you not have a list with the sets currently in Standard?

**Comment by glacials** [comment]
You should see something like this, with the sets currently in Standard on the left. Do you not?

![screenshot of whatsinstandard.com](https://user-images.githubusercontent.com/438911/44246024-cd81d280-a190-11e8-8fad-6ea3bcf3f1fe.png)

**Comment by DominusMaximus** [comment]
Ok now I understand the setup you went with. It didn't occur to me that those first 2 blocks would also represent what's currently in Standard. Alright then thanks.

**Comment by glacials** [comment]
No problem, thanks for bringing it up, It never occurred to me that this area could be misinterpreted as "sets dropping soon but not really all the sets in Standard". I can try to make that clearer.

**Comment by glacials** [comment]
Toying with something like this, could use a second opinion on whether it's too busy though.

<img width="1142" alt="screenshot 2018-08-17 10 06 04" src="https://user-images.githubusercontent.com/438911/44279148-31de7980-a205-11e8-9a5a-40a893ce5b17.png">

**Comment by DominusMaximus** [comment]
Yeah that looks good. The blue border around those 2 blocks combined with the heading would have cleared it up for me while still maintaining the clean look.

**Comment by glacials** [comment]
Coolio, thanks again for the feedback. Made the change.
