### ISSUE TITLE
bans: link cards to scryfall instead deckbox

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#94]
I think it's just the better site and displays the relevant information (also more) about a card better.

Nobody really wants to add banned cards to their collection or trade them.
Also, their card text is wrong, as they still not support `Energy` correctly...

**Comment by forstermatth** [comment]
I hadn't seen scryfall before. Cool.

**Comment by glacials** [comment]
I'd be cool with it, but the reason I used Deckbox was because it was stupidly simple to add their card-preview-on-hover code, which is really the only thing I want out of card linkifying. Does Skyfall have a similar library, or are there other libraries that could work with it?

**Comment by tooomm** [comment]
I never realized the on-hover, had js for deckbox disabled on your site. :)
The preview is pretty cool and helpful I have to say!

**Comment by tooomm** [comment]
I found a reddit post stating, that something like that is possible with scryfall, too:
https://www.reddit.com/r/magicTCG/comments/8d9cnh/mtg_wiki_has_updated_to_use_scryfall_tooltips/

**Comment by NilsEnevoldsen** [comment]
Give me a few days. I might submit a patch that uses some of the ScryfallLinks machinery, and you can decide if you like it.

**Comment by NilsEnevoldsen** [comment]
I've submitted a pull request. A few notes:

1. I realize it's not quite as clean as dropping in a third-party solution, and I don't mind if you reject the pull request.
2. I'm not a Node expert, so double-check that I didn't do anything dumb. Notably, I installed tippy.js with Node.
3. I realize that VueTippy was already part of the project. I kind of ignored that, and I hope it doesn't cause any problems to have tippy.js working side-by-side. I'm not sure how they interact.
4. I like dotted underlines to hint that a tooltip exists, but you can remove that if you like.
5. For each link, there are both a URL *and* data attributes that include the card name and set code. Yes, this makes an additional step when updating links, but updating the banlist is infrequent enough that I hope it's not too much trouble. (In ScryfallLinks, the data attributes are created from the link text, and then the URL is created from the data attributes. But here I removed that functionality to keep the code simpler.)
6. Including the set code in the URL and data attributes generally isn't necessary, but it will keep the link pointed at the Standard version of the card in case that card is quickly reprinted into a Commander set or something.
