### ISSUE TITLE
add logo to page

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#99]
Since we have a nice favicon setup now, why don't include it to the page itself for a better branding?

Could look like this:
![logo](https://user-images.githubusercontent.com/9874850/44653156-34538700-a9ee-11e8-8aaf-5bf2c28facd9.png)

**Comment by BlaKDetH** [comment]
This is a slight fix just linking the image from git.
<body>
    <div id="vue" class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="mt-5 mb-3 border-bottom">
				<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjwh%0D%0ARE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIKImh0dHA6Ly93d3cu%0D%0AdzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+Cgo8c3ZnIHg9IjAiIHk9IjAi%0D%0AIHdpZHRoPSI1NTAiIGhlaWdodD0iNTUwIiB2aWV3Qm94PSIwIDAgNTUwIDU1MCIgdmVyc2lvbj0i%0D%0AMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRw%0D%0AOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KCjxkZWZzPgo8cGF0aCBpZD0icXVlc3Rpb25tYXJr%0D%0AIiBkPSJNNDMxLC0xN2MwLDAsLTQ1LDAsLTc5LDI5YzAsMCwtMzQsMjksLTM0LDgyYzAsMCwwLDQ3%0D%0ALDMzLDc5YzAsMCwzMywzMiw4MCwzMmMwLDAsNDcsMCw4MCwtMzJjMCwwLDMyLC0zMiwzMiwtNzlj%0D%0AMCwwLDAsLTUyLC0zNCwtODJjMCwwLC0zNCwtMjksLTc4LC0yOVptLTgsMjkwYzAsMCwtMzksMCwt%0D%0ANjUsMjZjMCwwLC0yNywyNSwtMjcsNzVjMCwwLDAsNjMsMjAsMTA5YzAsMCwxOSw0Niw1MSw4MGMw%0D%0ALDAsMzIsMzUsODcsODNjMCwwLDQ3LDQyLDY5LDYzYzAsMCwyMSwyMSwzNiw0OGMwLDAsMTQsMjYs%0D%0AMTQsNTZjMCwwLDAsNjAsLTQ0LDEwMWMwLDAsLTQ1LDQxLC0xMTUsNDFjMCwwLC04MiwwLC0xMjEs%0D%0ALTQxYzAsMCwtMzgsLTQyLC02NSwtMTIzYzAsMCwtMjYsLTg0LC05NiwtODRjMCwwLC00MiwwLC03%0D%0AMSwzMGMwLDAsLTI5LDI5LC0yOSw2NGMwLDAsMCw3MSw0NiwxNDNjMCwwLDQ1LDczLDEzMywxMjFj%0D%0AMCwwLDg3LDQ4LDIwMyw0OGMwLDAsMTA4LDAsMTkxLC00MGMwLDAsODMsLTQwLDEyOCwtMTA5YzAs%0D%0AMCw0NiwtNjksNDYsLTE0OWMwLDAsMCwtNjQsLTI2LC0xMTJjMCwwLC0yNiwtNDcsLTYxLC04MmMw%0D%0ALDAsLTM2LC0zNSwtMTI4LC0xMTdjMCwwLC0yNSwtMjMsLTQwLC00MWMwLDAsLTE2LC0xNywtMjMs%0D%0ALTMyYzAsMCwtOCwtMTQsLTEyLC0yOWMwLDAsLTQsLTE0LC0xMiwtNTFjMCwwLC0xNCwtNzgsLTg5%0D%0ALC03OFoiIHRyYW5zZm9ybT0ic2NhbGUoMC4wMDEsLTAuMDAxKSIgLz4KPC9kZWZzPgoKPHBhdGgg%0D%0AZD0iTTc2LjYsMTIwLjFsMTMwLjYsLTM1QzIyMy4zLDgwLjgsMjMxLjUsNzguNiwyNDEsNzljMTAu%0D%0ANSwuOSwyMCw2LjQsMjYsMTVjNS4xLDgsNy4zLDE2LjIsMTEuNywzMi43bDY4LjgsMjU2LjdjNC4z%0D%0ALDE2LjEsNi41LDI0LjMsNi4xLDMzLjhjLS45LDEwLjUsLTYuNCwyMCwtMTUsMjZjLTgsNS4xLC0x%0D%0ANi4yLDcuMywtMzIuNiwxMS43TDE3NS43LDQ4OS44Yy0xNi4yLDQuNCwtMjQuNCw2LjYsLTMzLjgs%0D%0ANi4xYy0xMC41LC0uOSwtMjAsLTYuNCwtMjYuMSwtMTVjLTUuMSwtOCwtNy4zLC0xNi4yLC0xMS43%0D%0ALC0zMi42TDM1LjMsMTkxLjZDMzEsMTc1LjQsMjguOCwxNjcuMiwyOS4yLDE1Ny44YzEsLTEwLjUs%0D%0ANi41LC0yMCwxNS4xLC0yNi4xYzgsLTUuMSwxNi4yLC03LjMsMzIuNiwtMTEuN1oiIGZpbGw9IiNE%0D%0AM0QzRDMiIC8+Cgo8cGF0aCBkPSJNMjA3LjQsOTYuMUgzNDIuNmMxNi43LDAsMjUuMiwwLDM0LjIs%0D%0AMi44YzkuOSwzLjYsMTcuNywxMS40LDIxLjMsMjEuM2MyLjksOSwyLjksMTcuNSwyLjksMzQuNVY0%0D%0AMjAuNWMwLDE2LjcsMCwyNS4yLC0yLjksMzQuM2MtMy42LDkuOCwtMTEuNCwxNy42LC0yMS4zLDIx%0D%0ALjJjLTksMi45LC0xNy41LDIuOSwtMzQuNSwyLjlIMjA3LjRjLTE2LjcsMCwtMjUuMiwwLC0zNC4y%0D%0ALC0yLjljLTkuOSwtMy42LC0xNy43LC0xMS40LC0yMS4zLC0yMS4yQzE0OSw0NDUuNywxNDksNDM3%0D%0ALjIsMTQ5LDQyMC4yVjE1NC41YzAsLTE2LjgsMCwtMjUuMywyLjksLTM0LjNjMy42LC05LjksMTEu%0D%0ANCwtMTcuNywyMS4zLC0yMS4zYzksLTIuOCwxNy41LC0yLjgsMzQuNSwtMi44WiIgZmlsbD0iIzgw%0D%0AODA4MCIgLz4KCjxwYXRoIGQ9Ik0zNDEuNSw4NS4xbDEzMC42LDM1YzE2LjEsNC4zLDI0LjMsNi41%0D%0ALDMyLjMsMTEuNmM4LjYsNi4xLDE0LjEsMTUuNiwxNSwyNi4xYy41LDkuNCwtMS43LDE3LjYsLTYu%0D%0AMSwzNEw0NDQuNSw0NDguNmMtNC4zLDE2LjEsLTYuNSwyNC4zLC0xMS42LDMyLjNjLTYuMSw4LjYs%0D%0ALTE1LjYsMTQuMSwtMjYuMSwxNWMtOS40LC41LC0xNy43LC0xLjcsLTM0LjEsLTYuMUwyNDIuNSw0%0D%0ANTQuOWMtMTYuMiwtNC40LC0yNC40LC02LjYsLTMyLjQsLTExLjdjLTguNiwtNiwtMTQuMSwtMTUu%0D%0ANSwtMTUsLTI2Yy0uNSwtOS41LDEuNywtMTcuNyw2LjEsLTM0LjFMMjcwLDEyNi40QzI3NC40LDEx%0D%0AMC4yLDI3Ni42LDEwMiwyODEuNyw5NGM2LC04LjYsMTUuNSwtMTQuMSwyNiwtMTVjOS41LC0uNCwx%0D%0ANy43LDEuOCwzNC4xLDYuMloiIGZpbGw9IiMyODI4MjgiIC8+Cgo8dXNlIHhsaW5rOmhyZWY9IiNx%0D%0AdWVzdGlvbm1hcmsiIHRyYW5zZm9ybT0ibWF0cml4KDIyNyw2MC44LC02MC44LDIyNywyMjMuMiwz%0D%0ANzEuNikiIGZpbGw9IiNGRkZGRkYiIC8+Cgo8L3N2Zz4=" alt="logo" width="100" height="100&quot;" style="float:left;">
            <h1>What's in Standard?</h1>
            <div>
              <span class="low-distraction">for</span>
              <span>Magic: The Gathering</span>
              <span class="low-distraction"> / </span>
              <a href="http://standardhearth.com/" class="low-distraction">Hearthstone</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div v-if="false" class="col-md-5">
          <div class="spinner"></div>
        </div>

**Comment by BlaKDetH** [comment]
<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjwh%0D%0ARE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIKImh0dHA6Ly93d3cu%0D%0AdzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+Cgo8c3ZnIHg9IjAiIHk9IjAi%0D%0AIHdpZHRoPSI1NTAiIGhlaWdodD0iNTUwIiB2aWV3Qm94PSIwIDAgNTUwIDU1MCIgdmVyc2lvbj0i%0D%0AMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRw%0D%0AOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KCjxkZWZzPgo8cGF0aCBpZD0icXVlc3Rpb25tYXJr%0D%0AIiBkPSJNNDMxLC0xN2MwLDAsLTQ1LDAsLTc5LDI5YzAsMCwtMzQsMjksLTM0LDgyYzAsMCwwLDQ3%0D%0ALDMzLDc5YzAsMCwzMywzMiw4MCwzMmMwLDAsNDcsMCw4MCwtMzJjMCwwLDMyLC0zMiwzMiwtNzlj%0D%0AMCwwLDAsLTUyLC0zNCwtODJjMCwwLC0zNCwtMjksLTc4LC0yOVptLTgsMjkwYzAsMCwtMzksMCwt%0D%0ANjUsMjZjMCwwLC0yNywyNSwtMjcsNzVjMCwwLDAsNjMsMjAsMTA5YzAsMCwxOSw0Niw1MSw4MGMw%0D%0ALDAsMzIsMzUsODcsODNjMCwwLDQ3LDQyLDY5LDYzYzAsMCwyMSwyMSwzNiw0OGMwLDAsMTQsMjYs%0D%0AMTQsNTZjMCwwLDAsNjAsLTQ0LDEwMWMwLDAsLTQ1LDQxLC0xMTUsNDFjMCwwLC04MiwwLC0xMjEs%0D%0ALTQxYzAsMCwtMzgsLTQyLC02NSwtMTIzYzAsMCwtMjYsLTg0LC05NiwtODRjMCwwLC00MiwwLC03%0D%0AMSwzMGMwLDAsLTI5LDI5LC0yOSw2NGMwLDAsMCw3MSw0NiwxNDNjMCwwLDQ1LDczLDEzMywxMjFj%0D%0AMCwwLDg3LDQ4LDIwMyw0OGMwLDAsMTA4LDAsMTkxLC00MGMwLDAsODMsLTQwLDEyOCwtMTA5YzAs%0D%0AMCw0NiwtNjksNDYsLTE0OWMwLDAsMCwtNjQsLTI2LC0xMTJjMCwwLC0yNiwtNDcsLTYxLC04MmMw%0D%0ALDAsLTM2LC0zNSwtMTI4LC0xMTdjMCwwLC0yNSwtMjMsLTQwLC00MWMwLDAsLTE2LC0xNywtMjMs%0D%0ALTMyYzAsMCwtOCwtMTQsLTEyLC0yOWMwLDAsLTQsLTE0LC0xMiwtNTFjMCwwLC0xNCwtNzgsLTg5%0D%0ALC03OFoiIHRyYW5zZm9ybT0ic2NhbGUoMC4wMDEsLTAuMDAxKSIgLz4KPC9kZWZzPgoKPHBhdGgg%0D%0AZD0iTTc2LjYsMTIwLjFsMTMwLjYsLTM1QzIyMy4zLDgwLjgsMjMxLjUsNzguNiwyNDEsNzljMTAu%0D%0ANSwuOSwyMCw2LjQsMjYsMTVjNS4xLDgsNy4zLDE2LjIsMTEuNywzMi43bDY4LjgsMjU2LjdjNC4z%0D%0ALDE2LjEsNi41LDI0LjMsNi4xLDMzLjhjLS45LDEwLjUsLTYuNCwyMCwtMTUsMjZjLTgsNS4xLC0x%0D%0ANi4yLDcuMywtMzIuNiwxMS43TDE3NS43LDQ4OS44Yy0xNi4yLDQuNCwtMjQuNCw2LjYsLTMzLjgs%0D%0ANi4xYy0xMC41LC0uOSwtMjAsLTYuNCwtMjYuMSwtMTVjLTUuMSwtOCwtNy4zLC0xNi4yLC0xMS43%0D%0ALC0zMi42TDM1LjMsMTkxLjZDMzEsMTc1LjQsMjguOCwxNjcuMiwyOS4yLDE1Ny44YzEsLTEwLjUs%0D%0ANi41LC0yMCwxNS4xLC0yNi4xYzgsLTUuMSwxNi4yLC03LjMsMzIuNiwtMTEuN1oiIGZpbGw9IiNE%0D%0AM0QzRDMiIC8+Cgo8cGF0aCBkPSJNMjA3LjQsOTYuMUgzNDIuNmMxNi43LDAsMjUuMiwwLDM0LjIs%0D%0AMi44YzkuOSwzLjYsMTcuNywxMS40LDIxLjMsMjEuM2MyLjksOSwyLjksMTcuNSwyLjksMzQuNVY0%0D%0AMjAuNWMwLDE2LjcsMCwyNS4yLC0yLjksMzQuM2MtMy42LDkuOCwtMTEuNCwxNy42LC0yMS4zLDIx%0D%0ALjJjLTksMi45LC0xNy41LDIuOSwtMzQuNSwyLjlIMjA3LjRjLTE2LjcsMCwtMjUuMiwwLC0zNC4y%0D%0ALC0yLjljLTkuOSwtMy42LC0xNy43LC0xMS40LC0yMS4zLC0yMS4yQzE0OSw0NDUuNywxNDksNDM3%0D%0ALjIsMTQ5LDQyMC4yVjE1NC41YzAsLTE2LjgsMCwtMjUuMywyLjksLTM0LjNjMy42LC05LjksMTEu%0D%0ANCwtMTcuNywyMS4zLC0yMS4zYzksLTIuOCwxNy41LC0yLjgsMzQuNSwtMi44WiIgZmlsbD0iIzgw%0D%0AODA4MCIgLz4KCjxwYXRoIGQ9Ik0zNDEuNSw4NS4xbDEzMC42LDM1YzE2LjEsNC4zLDI0LjMsNi41%0D%0ALDMyLjMsMTEuNmM4LjYsNi4xLDE0LjEsMTUuNiwxNSwyNi4xYy41LDkuNCwtMS43LDE3LjYsLTYu%0D%0AMSwzNEw0NDQuNSw0NDguNmMtNC4zLDE2LjEsLTYuNSwyNC4zLC0xMS42LDMyLjNjLTYuMSw4LjYs%0D%0ALTE1LjYsMTQuMSwtMjYuMSwxNWMtOS40LC41LC0xNy43LC0xLjcsLTM0LjEsLTYuMUwyNDIuNSw0%0D%0ANTQuOWMtMTYuMiwtNC40LC0yNC40LC02LjYsLTMyLjQsLTExLjdjLTguNiwtNiwtMTQuMSwtMTUu%0D%0ANSwtMTUsLTI2Yy0uNSwtOS41LDEuNywtMTcuNyw2LjEsLTM0LjFMMjcwLDEyNi40QzI3NC40LDEx%0D%0AMC4yLDI3Ni42LDEwMiwyODEuNyw5NGM2LC04LjYsMTUuNSwtMTQuMSwyNiwtMTVjOS41LC0uNCwx%0D%0ANy43LDEuOCwzNC4xLDYuMloiIGZpbGw9IiMyODI4MjgiIC8+Cgo8dXNlIHhsaW5rOmhyZWY9IiNx%0D%0AdWVzdGlvbm1hcmsiIHRyYW5zZm9ybT0ibWF0cml4KDIyNyw2MC44LC02MC44LDIyNywyMjMuMiwz%0D%0ANzEuNikiIGZpbGw9IiNGRkZGRkYiIC8+Cgo8L3N2Zz4=" alt="logo" width="100" height="100&quot;" style="float:left;">
            <h1>What's in Standard?</h1>

**Comment by BlaKDetH** [comment]
<body>
    <div id="vue" class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="mt-5 mb-3 border-bottom">
				<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjwh%0D%0ARE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIKImh0dHA6Ly93d3cu%0D%0AdzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+Cgo8c3ZnIHg9IjAiIHk9IjAi%0D%0AIHdpZHRoPSI1NTAiIGhlaWdodD0iNTUwIiB2aWV3Qm94PSIwIDAgNTUwIDU1MCIgdmVyc2lvbj0i%0D%0AMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRw%0D%0AOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KCjxkZWZzPgo8cGF0aCBpZD0icXVlc3Rpb25tYXJr%0D%0AIiBkPSJNNDMxLC0xN2MwLDAsLTQ1LDAsLTc5LDI5YzAsMCwtMzQsMjksLTM0LDgyYzAsMCwwLDQ3%0D%0ALDMzLDc5YzAsMCwzMywzMiw4MCwzMmMwLDAsNDcsMCw4MCwtMzJjMCwwLDMyLC0zMiwzMiwtNzlj%0D%0AMCwwLDAsLTUyLC0zNCwtODJjMCwwLC0zNCwtMjksLTc4LC0yOVptLTgsMjkwYzAsMCwtMzksMCwt%0D%0ANjUsMjZjMCwwLC0yNywyNSwtMjcsNzVjMCwwLDAsNjMsMjAsMTA5YzAsMCwxOSw0Niw1MSw4MGMw%0D%0ALDAsMzIsMzUsODcsODNjMCwwLDQ3LDQyLDY5LDYzYzAsMCwyMSwyMSwzNiw0OGMwLDAsMTQsMjYs%0D%0AMTQsNTZjMCwwLDAsNjAsLTQ0LDEwMWMwLDAsLTQ1LDQxLC0xMTUsNDFjMCwwLC04MiwwLC0xMjEs%0D%0ALTQxYzAsMCwtMzgsLTQyLC02NSwtMTIzYzAsMCwtMjYsLTg0LC05NiwtODRjMCwwLC00MiwwLC03%0D%0AMSwzMGMwLDAsLTI5LDI5LC0yOSw2NGMwLDAsMCw3MSw0NiwxNDNjMCwwLDQ1LDczLDEzMywxMjFj%0D%0AMCwwLDg3LDQ4LDIwMyw0OGMwLDAsMTA4LDAsMTkxLC00MGMwLDAsODMsLTQwLDEyOCwtMTA5YzAs%0D%0AMCw0NiwtNjksNDYsLTE0OWMwLDAsMCwtNjQsLTI2LC0xMTJjMCwwLC0yNiwtNDcsLTYxLC04MmMw%0D%0ALDAsLTM2LC0zNSwtMTI4LC0xMTdjMCwwLC0yNSwtMjMsLTQwLC00MWMwLDAsLTE2LC0xNywtMjMs%0D%0ALTMyYzAsMCwtOCwtMTQsLTEyLC0yOWMwLDAsLTQsLTE0LC0xMiwtNTFjMCwwLC0xNCwtNzgsLTg5%0D%0ALC03OFoiIHRyYW5zZm9ybT0ic2NhbGUoMC4wMDEsLTAuMDAxKSIgLz4KPC9kZWZzPgoKPHBhdGgg%0D%0AZD0iTTc2LjYsMTIwLjFsMTMwLjYsLTM1QzIyMy4zLDgwLjgsMjMxLjUsNzguNiwyNDEsNzljMTAu%0D%0ANSwuOSwyMCw2LjQsMjYsMTVjNS4xLDgsNy4zLDE2LjIsMTEuNywzMi43bDY4LjgsMjU2LjdjNC4z%0D%0ALDE2LjEsNi41LDI0LjMsNi4xLDMzLjhjLS45LDEwLjUsLTYuNCwyMCwtMTUsMjZjLTgsNS4xLC0x%0D%0ANi4yLDcuMywtMzIuNiwxMS43TDE3NS43LDQ4OS44Yy0xNi4yLDQuNCwtMjQuNCw2LjYsLTMzLjgs%0D%0ANi4xYy0xMC41LC0uOSwtMjAsLTYuNCwtMjYuMSwtMTVjLTUuMSwtOCwtNy4zLC0xNi4yLC0xMS43%0D%0ALC0zMi42TDM1LjMsMTkxLjZDMzEsMTc1LjQsMjguOCwxNjcuMiwyOS4yLDE1Ny44YzEsLTEwLjUs%0D%0ANi41LC0yMCwxNS4xLC0yNi4xYzgsLTUuMSwxNi4yLC03LjMsMzIuNiwtMTEuN1oiIGZpbGw9IiNE%0D%0AM0QzRDMiIC8+Cgo8cGF0aCBkPSJNMjA3LjQsOTYuMUgzNDIuNmMxNi43LDAsMjUuMiwwLDM0LjIs%0D%0AMi44YzkuOSwzLjYsMTcuNywxMS40LDIxLjMsMjEuM2MyLjksOSwyLjksMTcuNSwyLjksMzQuNVY0%0D%0AMjAuNWMwLDE2LjcsMCwyNS4yLC0yLjksMzQuM2MtMy42LDkuOCwtMTEuNCwxNy42LC0yMS4zLDIx%0D%0ALjJjLTksMi45LC0xNy41LDIuOSwtMzQuNSwyLjlIMjA3LjRjLTE2LjcsMCwtMjUuMiwwLC0zNC4y%0D%0ALC0yLjljLTkuOSwtMy42LC0xNy43LC0xMS40LC0yMS4zLC0yMS4yQzE0OSw0NDUuNywxNDksNDM3%0D%0ALjIsMTQ5LDQyMC4yVjE1NC41YzAsLTE2LjgsMCwtMjUuMywyLjksLTM0LjNjMy42LC05LjksMTEu%0D%0ANCwtMTcuNywyMS4zLC0yMS4zYzksLTIuOCwxNy41LC0yLjgsMzQuNSwtMi44WiIgZmlsbD0iIzgw%0D%0AODA4MCIgLz4KCjxwYXRoIGQ9Ik0zNDEuNSw4NS4xbDEzMC42LDM1YzE2LjEsNC4zLDI0LjMsNi41%0D%0ALDMyLjMsMTEuNmM4LjYsNi4xLDE0LjEsMTUuNiwxNSwyNi4xYy41LDkuNCwtMS43LDE3LjYsLTYu%0D%0AMSwzNEw0NDQuNSw0NDguNmMtNC4zLDE2LjEsLTYuNSwyNC4zLC0xMS42LDMyLjNjLTYuMSw4LjYs%0D%0ALTE1LjYsMTQuMSwtMjYuMSwxNWMtOS40LC41LC0xNy43LC0xLjcsLTM0LjEsLTYuMUwyNDIuNSw0%0D%0ANTQuOWMtMTYuMiwtNC40LC0yNC40LC02LjYsLTMyLjQsLTExLjdjLTguNiwtNiwtMTQuMSwtMTUu%0D%0ANSwtMTUsLTI2Yy0uNSwtOS41LDEuNywtMTcuNyw2LjEsLTM0LjFMMjcwLDEyNi40QzI3NC40LDEx%0D%0AMC4yLDI3Ni42LDEwMiwyODEuNyw5NGM2LC04LjYsMTUuNSwtMTQuMSwyNiwtMTVjOS41LC0uNCwx%0D%0ANy43LDEuOCwzNC4xLDYuMloiIGZpbGw9IiMyODI4MjgiIC8+Cgo8dXNlIHhsaW5rOmhyZWY9IiNx%0D%0AdWVzdGlvbm1hcmsiIHRyYW5zZm9ybT0ibWF0cml4KDIyNyw2MC44LC02MC44LDIyNywyMjMuMiwz%0D%0ANzEuNikiIGZpbGw9IiNGRkZGRkYiIC8+Cgo8L3N2Zz4=" alt="logo" width="100" height="100&quot;" style="float:left;">
            <h1>What's in Standard?</h1>
            <div>
              <span class="low-distraction">for</span>
              <span>Magic: The Gathering</span>
              <span class="low-distraction"> / </span>
              <a href="http://standardhearth.com/" class="low-distraction">Hearthstone</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div v-if="false" class="col-md-5">
          <div class="spinner"></div>
        </div>

**Comment by BlaKDetH** [comment]
[logo addition.txt](https://github.com/glacials/whatsinstandard/files/2375316/logo.addition.txt)

**Comment by BlaKDetH** [comment]
> <body>
    <div id="vue" class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="mt-5 mb-3 border-bottom">
				<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjwh%0D%0ARE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIKImh0dHA6Ly93d3cu%0D%0AdzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+Cgo8c3ZnIHg9IjAiIHk9IjAi%0D%0AIHdpZHRoPSI1NTAiIGhlaWdodD0iNTUwIiB2aWV3Qm94PSIwIDAgNTUwIDU1MCIgdmVyc2lvbj0i%0D%0AMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRw%0D%0AOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KCjxkZWZzPgo8cGF0aCBpZD0icXVlc3Rpb25tYXJr%0D%0AIiBkPSJNNDMxLC0xN2MwLDAsLTQ1LDAsLTc5LDI5YzAsMCwtMzQsMjksLTM0LDgyYzAsMCwwLDQ3%0D%0ALDMzLDc5YzAsMCwzMywzMiw4MCwzMmMwLDAsNDcsMCw4MCwtMzJjMCwwLDMyLC0zMiwzMiwtNzlj%0D%0AMCwwLDAsLTUyLC0zNCwtODJjMCwwLC0zNCwtMjksLTc4LC0yOVptLTgsMjkwYzAsMCwtMzksMCwt%0D%0ANjUsMjZjMCwwLC0yNywyNSwtMjcsNzVjMCwwLDAsNjMsMjAsMTA5YzAsMCwxOSw0Niw1MSw4MGMw%0D%0ALDAsMzIsMzUsODcsODNjMCwwLDQ3LDQyLDY5LDYzYzAsMCwyMSwyMSwzNiw0OGMwLDAsMTQsMjYs%0D%0AMTQsNTZjMCwwLDAsNjAsLTQ0LDEwMWMwLDAsLTQ1LDQxLC0xMTUsNDFjMCwwLC04MiwwLC0xMjEs%0D%0ALTQxYzAsMCwtMzgsLTQyLC02NSwtMTIzYzAsMCwtMjYsLTg0LC05NiwtODRjMCwwLC00MiwwLC03%0D%0AMSwzMGMwLDAsLTI5LDI5LC0yOSw2NGMwLDAsMCw3MSw0NiwxNDNjMCwwLDQ1LDczLDEzMywxMjFj%0D%0AMCwwLDg3LDQ4LDIwMyw0OGMwLDAsMTA4LDAsMTkxLC00MGMwLDAsODMsLTQwLDEyOCwtMTA5YzAs%0D%0AMCw0NiwtNjksNDYsLTE0OWMwLDAsMCwtNjQsLTI2LC0xMTJjMCwwLC0yNiwtNDcsLTYxLC04MmMw%0D%0ALDAsLTM2LC0zNSwtMTI4LC0xMTdjMCwwLC0yNSwtMjMsLTQwLC00MWMwLDAsLTE2LC0xNywtMjMs%0D%0ALTMyYzAsMCwtOCwtMTQsLTEyLC0yOWMwLDAsLTQsLTE0LC0xMiwtNTFjMCwwLC0xNCwtNzgsLTg5%0D%0ALC03OFoiIHRyYW5zZm9ybT0ic2NhbGUoMC4wMDEsLTAuMDAxKSIgLz4KPC9kZWZzPgoKPHBhdGgg%0D%0AZD0iTTc2LjYsMTIwLjFsMTMwLjYsLTM1QzIyMy4zLDgwLjgsMjMxLjUsNzguNiwyNDEsNzljMTAu%0D%0ANSwuOSwyMCw2LjQsMjYsMTVjNS4xLDgsNy4zLDE2LjIsMTEuNywzMi43bDY4LjgsMjU2LjdjNC4z%0D%0ALDE2LjEsNi41LDI0LjMsNi4xLDMzLjhjLS45LDEwLjUsLTYuNCwyMCwtMTUsMjZjLTgsNS4xLC0x%0D%0ANi4yLDcuMywtMzIuNiwxMS43TDE3NS43LDQ4OS44Yy0xNi4yLDQuNCwtMjQuNCw2LjYsLTMzLjgs%0D%0ANi4xYy0xMC41LC0uOSwtMjAsLTYuNCwtMjYuMSwtMTVjLTUuMSwtOCwtNy4zLC0xNi4yLC0xMS43%0D%0ALC0zMi42TDM1LjMsMTkxLjZDMzEsMTc1LjQsMjguOCwxNjcuMiwyOS4yLDE1Ny44YzEsLTEwLjUs%0D%0ANi41LC0yMCwxNS4xLC0yNi4xYzgsLTUuMSwxNi4yLC03LjMsMzIuNiwtMTEuN1oiIGZpbGw9IiNE%0D%0AM0QzRDMiIC8+Cgo8cGF0aCBkPSJNMjA3LjQsOTYuMUgzNDIuNmMxNi43LDAsMjUuMiwwLDM0LjIs%0D%0AMi44YzkuOSwzLjYsMTcuNywxMS40LDIxLjMsMjEuM2MyLjksOSwyLjksMTcuNSwyLjksMzQuNVY0%0D%0AMjAuNWMwLDE2LjcsMCwyNS4yLC0yLjksMzQuM2MtMy42LDkuOCwtMTEuNCwxNy42LC0yMS4zLDIx%0D%0ALjJjLTksMi45LC0xNy41LDIuOSwtMzQuNSwyLjlIMjA3LjRjLTE2LjcsMCwtMjUuMiwwLC0zNC4y%0D%0ALC0yLjljLTkuOSwtMy42LC0xNy43LC0xMS40LC0yMS4zLC0yMS4yQzE0OSw0NDUuNywxNDksNDM3%0D%0ALjIsMTQ5LDQyMC4yVjE1NC41YzAsLTE2LjgsMCwtMjUuMywyLjksLTM0LjNjMy42LC05LjksMTEu%0D%0ANCwtMTcuNywyMS4zLC0yMS4zYzksLTIuOCwxNy41LC0yLjgsMzQuNSwtMi44WiIgZmlsbD0iIzgw%0D%0AODA4MCIgLz4KCjxwYXRoIGQ9Ik0zNDEuNSw4NS4xbDEzMC42LDM1YzE2LjEsNC4zLDI0LjMsNi41%0D%0ALDMyLjMsMTEuNmM4LjYsNi4xLDE0LjEsMTUuNiwxNSwyNi4xYy41LDkuNCwtMS43LDE3LjYsLTYu%0D%0AMSwzNEw0NDQuNSw0NDguNmMtNC4zLDE2LjEsLTYuNSwyNC4zLC0xMS42LDMyLjNjLTYuMSw4LjYs%0D%0ALTE1LjYsMTQuMSwtMjYuMSwxNWMtOS40LC41LC0xNy43LC0xLjcsLTM0LjEsLTYuMUwyNDIuNSw0%0D%0ANTQuOWMtMTYuMiwtNC40LC0yNC40LC02LjYsLTMyLjQsLTExLjdjLTguNiwtNiwtMTQuMSwtMTUu%0D%0ANSwtMTUsLTI2Yy0uNSwtOS41LDEuNywtMTcuNyw2LjEsLTM0LjFMMjcwLDEyNi40QzI3NC40LDEx%0D%0AMC4yLDI3Ni42LDEwMiwyODEuNyw5NGM2LC04LjYsMTUuNSwtMTQuMSwyNiwtMTVjOS41LC0uNCwx%0D%0ANy43LDEuOCwzNC4xLDYuMloiIGZpbGw9IiMyODI4MjgiIC8+Cgo8dXNlIHhsaW5rOmhyZWY9IiNx%0D%0AdWVzdGlvbm1hcmsiIHRyYW5zZm9ybT0ibWF0cml4KDIyNyw2MC44LC02MC44LDIyNywyMjMuMiwz%0D%0ANzEuNikiIGZpbGw9IiNGRkZGRkYiIC8+Cgo8L3N2Zz4=" alt="logo" width="100" height="100&quot;" style="float:left;">
            <h1>What's in Standard?</h1>
            <div>
              <span class="low-distraction">for</span>
              <span>Magic: The Gathering</span>
              <span class="low-distraction"> / </span>
              <a href="http://standardhearth.com/" class="low-distraction">Hearthstone</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div v-if="false" class="col-md-5">
          <div class="spinner"></div>
        </div>

>

**Comment by glacials** [comment]
Feel free to open a pull request!
